name: "Analysis & Build crx"

on:
  push:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ["javascript"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Auto Minify
        uses: nizarmah/auto-minify@master

      - name: Override
        run: |
          python min.js-override.py

      - name: Zip
        run: |
          chmod +x build.sh
          ./build.sh
          zip -q -r Pomodoro-Improved-build.zip build/*

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          path: Pomodoro-Improved-build.zip
