name: "Build crx"
on:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Minify Action
        uses: anthonyftwang/minify-action@v1.0.1
      - name: Zip
        run: |
          bash build/build.sh
          cd build/
          zip -q -r Pomodoro-Improved-build.zip pomodoro-improved-build/*
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Pomodoro-Improved-build
          path: build/Pomodoro-Improved-build.zip
